name: Build and Release CyberSnoop

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Verify installer exists
      run: |
        if (Test-Path "CyberSnoop-Setup.exe") {
          Write-Host "✅ Using pre-built CyberSnoop-Setup.exe"
          Write-Host "File size: $((Get-Item CyberSnoop-Setup.exe).Length) bytes"
        } else {
          Write-Host "❌ CyberSnoop-Setup.exe not found, creating fallback installer..."
          pip install -r requirements.txt
          cd desktop_app
          pyinstaller --onefile --windowed --name CyberSnoop enhanced_cybersnoop_desktop.py
          copy dist\CyberSnoop.exe ..\CyberSnoop-Setup.exe
        }

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: CyberSnoop ${{ github.ref_name }}
        body: |
          🛡️ **CyberSnoop ${{ github.ref_name }} - Production Release**
          
          ## 📥 **Easy Installation**
          Download `CyberSnoop-Setup.exe` and run it. The installer will:
          - Download and install CyberSnoop automatically
          - Create desktop shortcut
          - Add to Start Menu
          - Install all dependencies

          ## ✨ **Features**
          - Real-time Network Monitoring (12+ packet categories)
          - AI-Powered Threat Detection (Machine Learning)
          - SIEM Integration (Splunk, ELK, QRadar, Microsoft Sentinel)
          - Cloud Monitoring (Azure, GCP - AWS support planned)
          - Compliance Reporting (PCI DSS, HIPAA, GDPR, SOX)
          - Professional React Dashboard
          - Complete API Access

          ## 🎯 **100% Free & Open Source**
          All enterprise features included at no cost.

          ## 💻 **System Requirements**
          - Windows 10/11 (64-bit)
          - Minimum: Intel i5 (4th gen) or AMD Ryzen 5, 8GB RAM
          - Recommended: Intel i7 (8th gen+) or AMD Ryzen 7, 16GB RAM
          - Python 3.11+ (automatically managed by installer)
          - Administrator privileges for network monitoring

          ## 🐛 **Support**
          Report issues: https://github.com/${{ github.repository }}/issues
        files: |
          CyberSnoop-Setup.exe
        draft: false
        prerelease: false
